feat: Controllers Code (#17)
ydataai/go-core pull request #18
Opened 2021-11-10 19:34 UTC by wsalles

Avoiding repeated code from controllers.

closes #17

2021-11-10 20:37 UTC, renatoaguimaraes requested changes

2021-11-10 20:37 UTC, renatoaguimaraes commented on pkg/common/logger/logger.go
> +type LoggerConfig struct {
Should implements the  `LoadFromEnvVars()` interface.

```
func (l * LoggerConfig) LoadFromEnvVars() error {
	return envconfig.Process("", l)
}
```

2021-11-10 20:37 UTC, renatoaguimaraes commented on pkg/common/logger/logger.go
> +	if err := envconfig.Process("", &config); err != nil {
We can use `InitConfigurationVariables(configs []ConfigurationVariables)` to initialize the logger config.

2021-11-10 20:37 UTC, renatoaguimaraes commented on pkg/common/logger/logger.go
> +		panic(err.Error())
We don't need to 'panic' here, just follow with the default log level.

2021-11-11 11:50 UTC, renatoaguimaraes requested changes

2021-11-11 11:50 UTC, renatoaguimaraes commented on pkg/common/logger/logger.go
> +func NewConfiguration(level, output string, cf, trim, hk bool) *Configuration {
For this constructor, we don't need to pass these parameters, they come from environment variables.

2021-11-11 11:50 UTC, renatoaguimaraes commented on pkg/common/logger/logger.go
> +type Configuration struct {
I think we can call it as `LoggingConfiguration` or `LoggerConfiguration`.

2021-11-11 12:46 UTC, wsalles commented on pkg/common/logger/logger.go
> +type Configuration struct {
according with Codacy, package logger and LoggerConfiguration causes stutter 🤣 
and then failed... we can rename the package from logger to logging or think like that

2021-11-11 13:07 UTC, renatoaguimaraes approved these changes

2021-11-11 13:09 UTC, merged