feat: Include HealthCheck in server pkg
ydataai/go-core pull request #44
Opened 2021-12-01 15:17 UTC by wsalles

Closes [PLT-56]

2021-12-01 18:17 UTC, renatoaguimaraes approved these changes

2021-12-01 18:17 UTC, renatoaguimaraes commented on pkg/common/server/server.go
> +func (s *Server) UseHealthCheck() {
The health check is optional? I think we can call at Server constructor.
For k8s applications the probes are very important, both /healthz for Liveness and /readyz for Readiness.
For example, for readiness we can create a method with a func parameter thats need to implemented for each service.

2021-12-01 18:18 UTC, renatoaguimaraes requested changes
Let's think about readyz and healthz

2021-12-02 08:58 UTC, portellaa reviewed
We could do something as `AddHealthz` and `AddReadyz` this could be enabled by the user if he wants.
I can see we needing this all the time, but i think it doesn't hurt to have this configurable

2021-12-02 08:58 UTC, portellaa commented on pkg/common/server/middlewares.go
> +}
well, perhaps they don't fit very well as middleware's

2021-12-02 16:04 UTC, portellaa reviewed
mixed feelings about the names for AddHealthz and AddReadyz 🤔 
perhaps something different, what do you think @renatoaguimaraes @wsalles ?

2021-12-02 16:04 UTC, portellaa commented on pkg/common/server/server.go
> +func (s *Server) AddHealthz() {
are we receiving an endpoint here if want to override?

2021-12-02 16:04 UTC, portellaa commented on pkg/common/server/server.go
> +func (s *Server) AddReadyz() {
same as healthz and the callback

2021-12-02 17:03 UTC, wsalles commented on pkg/common/server/server.go
> +func (s *Server) AddHealthz() {
about the name, I liked it!
now the endpoint is highly configurable. please, see the latest changes and tell me what do you think?

2021-12-02 17:04 UTC, wsalles commented on pkg/common/server/server.go
> +func (s *Server) AddReadyz() {
callback also to healthz? 🤔 
is it necessary?

2021-12-02 18:59 UTC, portellaa commented on pkg/common/helpers/utils.go
> +func FirstStringOfArrayWithFallback(list []string, fallback ...string) string {
why is the fallback a cvarg?

2021-12-02 18:59 UTC, portellaa commented on pkg/common/helpers/utils.go
> +}
why do we need this?

2021-12-02 18:59 UTC, portellaa commented on pkg/common/helpers/utils.go
> +}
and this?

2021-12-02 19:06 UTC, portellaa commented on pkg/common/helpers/utils.go
> +func FirstStringOfArrayWithFallback(list []string, fallback string) string {
i would move this method to the server and make it private, don't see we needing it

2021-12-02 19:15 UTC, wsalles commented on pkg/common/helpers/utils.go
> +func FirstStringOfArrayWithFallback(list []string, fallback string) string {
done.

2021-12-02 19:37 UTC, portellaa approved these changes

2021-12-02 19:58 UTC, renatoaguimaraes approved these changes

2021-12-02 20:17 UTC, merged