feat(server): include callback for when the server is ready + fix bugs
ydataai/go-core pull request #50
Opened 2022-01-10 20:02 UTC by wsalles

closes [PLT-134]

2022-01-10 20:13 UTC, renatoaguimaraes commented on pkg/common/server/server.go
> -		s.logger.Infof("Server exiting")
Good, that's a dead code because `s.httpServer.ListenAndServe()` blocks the execution.

2022-01-10 20:16 UTC, renatoaguimaraes requested changes

2022-01-10 20:16 UTC, renatoaguimaraes commented on pkg/common/server/server.go
> +func (s *Server) WaitingToBeReady(callback func()) {
Shouldn't be exported and the callback can be passed in the `Run` method as a parameter.

2022-01-10 20:33 UTC, wsalles commented on pkg/common/server/server.go
> +func (s *Server) WaitingToBeReady(callback func()) {
Good idea! Thanks @renatoaguimaraes

2022-01-10 23:41 UTC, portellaa reviewed
Is this the best way to know that the server is ready?

2022-01-11 01:31 UTC, wsalles commented
> Is this the best way to know that the server is ready?

that's it or create requests to check if it's ready...
now, if there is a better way for this case, I don't know.

2022-01-11 12:12 UTC, renatoaguimaraes commented
> > Is this the best way to know that the server is ready?
> 
> that's it or create requests to check if it's ready... now, if there is a better way for this case, I don't know.

Maybe a GET operation on /readyz endpoint is better to know if the server is initialized. What do you think?

2022-01-11 16:03 UTC, portellaa approved these changes

2022-01-11 16:27 UTC, merged