feat(vault): add operations and development mode support
ydataai/go-core pull request #62
Opened 2022-02-03 20:36 UTC by wsalles

closes [PLT-242]

2022-02-04 01:02 UTC, portellaa commented on pkg/common/clients/vault_client.go
> +	secret, err := vc.client.Logical().List(path)
i would call this data, instead of secret

2022-02-04 09:42 UTC, wsalles commented on pkg/common/clients/vault_client.go
> +	go vc.renew()
it is only necessary to renew when you need to take the token from SA and "write".
And then, for local testing, it isn't necessary. 
just have the token and that's it.

2022-02-04 09:51 UTC, wsalles commented on pkg/common/clients/vault_client.go
> +	_, err := vc.client.Logical().Write(fmt.Sprintf("%s/data/%s", path, name), map[string]interface{}{
you're right! since we are adding the path parameter, we have already passed the real path.

2022-02-04 10:16 UTC, wsalles commented on pkg/common/clients/vault_client.go
> +	secret, err := vc.client.Logical().List(path)
doesn't it look weird?
`return data.Data["keys"], nil`

2022-02-04 10:46 UTC, wsalles commented on pkg/common/clients/vault_client.go
> +	}
let's think of a better way...

2022-02-04 17:38 UTC, renatoaguimaraes requested changes

2022-02-04 17:38 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +}
I think we can simplify this method. I don't like nested statements because it can be really hard to read and understand the logic. Following my suggestion:

```suggestion
// Patch ...
func (vc *VaultClient) Patch(path string, data map[string]interface{}) error {
	vc.logger.Infof("[Vault] Adding the '%s' ☄️", path)
	// try to patch the path
	_, err := vc.client.Logical().JSONMergePatch(context.Background(), path, data)
	if err == nil {
		return nil
	}
	// If it's a 405, that probably means the server is running a pre-1.9
	// Vault version that doesn't support the HTTP PATCH method.
	if re, ok := err.(*api.ResponseError); ok && re.StatusCode != 405 {
		return fmt.Errorf("[Vault] Unable to add the path: '%s' 😱. Err: %v", path, err)
	}
	// get data to update it in memory
	existingData, err := vc.Get(path)
	if err != nil {
		return fmt.Errorf("[Vault] Unable to get the path: '%s' 😱. Err: %v", path, err)
	}
	// if exists data, then update
	if existingData != nil {
		// if it exists, then update
		for key, value := range data {
			existingData[key] = value
		}
		if err := vc.Put(path, existingData); err != nil {
			return err
		}
		return nil
	}
	// it doesn't exists, create
	if err := vc.Put(path, data); err != nil {
		return err
	}
	vc.logger.Infof("[Vault] Patched the '%s' ☄️", path)
	return nil
}
```

2022-02-04 17:40 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +	secret, err := vc.client.Logical().List(path)
> data.Data

You just need to return `data.Data`.

2022-02-04 17:42 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +	secret, err := vc.client.Logical().List(path)
> doesn't it look weird? `return data.Data["keys"], nil`

Where "keys" come from? You just need to return `data.Data`.

2022-02-04 17:46 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +	}
That's a good idea, we can have an `Authenticator` interface with the `login` method and so two implementations of that interface, for example: `K8sAuthenticator` and `TokenAuthenticaticator`.

2022-02-04 17:47 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +}
Simple and flat methods are always welcome 😃.

2022-02-04 17:59 UTC, renatoaguimaraes requested changes

2022-02-04 17:59 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +	go vc.renew()
The root token never expires.

2022-02-04 18:02 UTC, portellaa commented
so my suggestion for the authentication part is:

```go
type Authenticator interface {
  func authenticate(vc *VaultClient) error
}

type K8sAuthenticator struct {
    configuration Configuration // if any for this authenticator
}

func (a *K8sAuthenticator) authenticate(vc *VaultClient) error {
	vc.logger.Info("performing vault k8s login.")
	// reads jwt from service account
	jwt, err := os.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/token")
	if err != nil {
		return fmt.Errorf("unable to read file containing service account token: %v 😱", err)
	}
	params := map[string]interface{}{
		"jwt":  string(jwt),
		"role": vc.role, // the name of the role in Vault that was created with this app's Kubernetes service account bound to it
	}
	// perform login
	secret, err := vc.client.Logical().Write("auth/kubernetes/login", params)
	if err != nil {
		return fmt.Errorf("unable to log in with Kubernetes auth: %v 😱", err)
	}
	if secret == nil || secret.Auth == nil || secret.Auth.ClientToken == "" {
		return errors.New("login response did not return client token 😱")
	}
	// client update with the access token
	vc.logger.Info("login: client logged in successfully 🔑")
	token := strings.TrimSuffix(secret.Auth.ClientToken, "\n")
	vc.client.SetToken(token)
	// stores login response secret
	vc.secret = secret

	// do the token renewal cycle
	go vc.renew()

	return nil
}

type LocalAuthenticator struct {
    configuration Configuration // if any for this authenticator
}

func (a *K8sAuthenticator) authenticate(vc *VaultClient) error {
	// Make sure it's development mode
	if vc.configuration.VaultDevMode {
		vc.logger.Info("[development mode] performing vault login.")
		if vc.configuration.VaultToken == "" {
			return errors.New("unable to get token as env var ('VAULT_TOKEN') 😱")
		}
		vc.client.SetToken(vc.configuration.VaultToken)
		return nil
	}
}
```



the VaultClient constructor for example:

```go
func NewVaultClient(role string, configuration VaultClientConfiguration, logger logging.Logger, authenticator Authenticator) (*VaultClient, error) {
        config := &api.Config{Address: configuration.VaultURL}

        if authenticator == nil {
              authenticator = NewK8sAuthenticator() // for example or we can throw an error, for example.
        }

	client, err := api.NewClient(config)
	if err != nil {
		return nil, err
	}

	vc := &VaultClient{
		configuration: configuration,
		role:          role,
		logger:        logger,
		client:        client,
	}

	if err = authenticator.authenticate(vc); err != nil {
		return nil, err
	}

	return vc, nil
}
```

there is no login any more, all that logic goes into the authenticator.

@wsalles this is what i was saying about the authentication part

2022-02-04 18:11 UTC, renatoaguimaraes commented
> so my suggestion for the authentication part is:
> 
> ```go
> type Authenticator interface {
>   func Authenticate(vc *VaultClient) error
> }
> 
> type K8sAuthenticator struct {
>     configuration Configuration // if any for this authenticator
> }
> 
> func (a *K8sAuthenticator) Authenticate(vc *VaultClient) error {
> 	vc.logger.Info("performing vault k8s login.")
> 	// reads jwt from service account
> 	jwt, err := os.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/token")
> 	if err != nil {
> 		return fmt.Errorf("unable to read file containing service account token: %v 😱", err)
> 	}
> 	params := map[string]interface{}{
> 		"jwt":  string(jwt),
> 		"role": vc.role, // the name of the role in Vault that was created with this app's Kubernetes service account bound to it
> 	}
> 	// perform login
> 	secret, err := vc.client.Logical().Write("auth/kubernetes/login", params)
> 	if err != nil {
> 		return fmt.Errorf("unable to log in with Kubernetes auth: %v 😱", err)
> 	}
> 	if secret == nil || secret.Auth == nil || secret.Auth.ClientToken == "" {
> 		return errors.New("login response did not return client token 😱")
> 	}
> 	// client update with the access token
> 	vc.logger.Info("login: client logged in successfully 🔑")
> 	token := strings.TrimSuffix(secret.Auth.ClientToken, "\n")
> 	vc.client.SetToken(token)
> 	// stores login response secret
> 	vc.secret = secret
> 
> 	// do the token renewal cycle
> 	go vc.renew()
> 
> 	return nil
> }
> 
> type LocalAuthenticator struct {
>     configuration Configuration // if any for this authenticator
> }
> 
> func (a *K8sAuthenticator) Authenticate(vc *VaultClient) error {
> 	// Make sure it's development mode
> 	if vc.configuration.VaultDevMode {
> 		vc.logger.Info("[development mode] performing vault login.")
> 		if vc.configuration.VaultToken == "" {
> 			return errors.New("unable to get token as env var ('VAULT_TOKEN') 😱")
> 		}
> 		vc.client.SetToken(vc.configuration.VaultToken)
> 		return nil
> 	}
> }
> ```
> 
> the VaultClient constructor for example:
> 
> ```go
> func NewVaultClient(role string, configuration VaultClientConfiguration, logger logging.Logger, authenticator Authenticator) (*VaultClient, error) {
>         config := &api.Config{Address: configuration.VaultURL}
> 
>         if authenticator == nil {
>               authenticator = NewK8sAuthenticator() // for example or we can throw an error, for example.
>         }
> 
> 	client, err := api.NewClient(config)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	vc := &VaultClient{
> 		configuration: configuration,
> 		role:          role,
> 		logger:        logger,
> 		client:        client,
> 	}
> 
> 	if err = authenticator.Authenticate(vc); err != nil {
> 		return nil, err
> 	}
> 
> 	return vc, nil
> }
> ```
> 
> there is no login any more, all that logic goes into the authenticator.
> 
> @wsalles this is what i was saying about the authentication part

In this way we don't need the development mode configuration any more. The user just need to instantiate the right authenticator.

2022-02-07 14:11 UTC, wsalles commented on pkg/common/clients/vault_client.go
> +	secret, err := vc.client.Logical().List(path)
So, "keys" comes from the `client.Logical().List(path)`

output with just `data.Data`:
```
map[keys:[2222 4567 5553 5554 5555]] 
```

2022-02-07 17:10 UTC, portellaa requested changes
The renew is part of the authenticator, so let's move it there and do the logic there.

in the case of the `K8sAuthenticator`, it's the only that makes sense to have the renew process.

so i suggest we store the reference to the authenticator in the VaultClient, just to make sure is not garbage collected.

2022-02-07 17:10 UTC, portellaa commented on pkg/common/clients/vault_client.go
> +func (vc *VaultClient) renew(authenticator Authenticator) {
this is a method that depends on the authenticator itself, it's logic is only for the k8s (in this case) so it makes sense that it goes into the authenticator

2022-02-07 17:10 UTC, portellaa commented on pkg/common/clients/vault_client.go
> +			authenticator.Authenticate(vc)
this doesn't makes sense

2022-02-07 17:21 UTC, renatoaguimaraes approved these changes

2022-02-07 17:21 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client.go
> +func (vc *VaultClient) renew(authenticator Authenticator) {
I agree with @portellaa.

2022-02-07 17:21 UTC, renatoaguimaraes commented on pkg/common/clients/vault_client_authenticator.go
> +
I agree.

2022-02-07 18:50 UTC, portellaa commented
@wsalles please split the file authenticator into multiple files 🙏

2022-02-07 19:59 UTC, portellaa approved these changes

2022-02-07 20:13 UTC, renatoaguimaraes approved these changes

2022-02-07 20:18 UTC, merged